/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectbd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class ListaElevi extends javax.swing.JFrame {

    String nr_e = null;
    String nume_e=null;
    String init_t=null;
    String prenume_e=null;
    MainExamen me;
    /**
     * Creates new form ListaElevi
     */
    public ListaElevi() {
        initComponents();
         getConnection();
        Show_Elev();
    }

    int pos = 0;
    
     public Connection getConnection(){
        Connection con=null;
        
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examencapacitate","root","");
           // JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(MainSc.class.getName()).log(Level.SEVERE, null, ex);
           // JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }
    }
     
      public ArrayList<Elev> getElevList(){
             ArrayList<Elev> elevList= new ArrayList<Elev>();
            Connection con= getConnection();
            String query = "SELECT * FROM elev";
            
            Statement st;
            ResultSet rs;
        try {
            
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Elev elev;
            while(rs.next()){
                elev = new Elev(rs.getInt("nr_e"),rs.getString("nume_e"),rs.getString("prenume_e"),rs.getString("init_t"),rs.getInt("nr_sc"));
                elevList.add(elev);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainSc.class.getName()).log(Level.SEVERE, null, ex);
        }
        return elevList;
        
    }
    
    
    public void Show_Elev(){
        ArrayList<Elev> list = getElevList();
        DefaultTableModel model= (DefaultTableModel)tbl_listaelevi.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[5];
        for (int i= 0;i< list.size();i++){
            row[0]= list.get(i).getEnr();
            row[1]= list.get(i).getNumee();
            row[2]= list.get(i).getPrene();
            row[3]= list.get(i).getInit();
            row[4]= list.get(i).getScnr();
         
            
            model.addRow(row);
            
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listaelevi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_listaelevi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numar elev", "Nume elev", "Prenume elev", "Initiala tatalui", "Numar scoala"
            }
        ));
        tbl_listaelevi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listaeleviMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_listaelevi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_listaeleviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listaeleviMouseClicked
        // TODO add your handling code here:
        
        int i = tbl_listaelevi.getSelectedRow();
        
        nr_e = Integer.toString(getElevList().get(i).getEnr());   
        nume_e=getElevList().get(i).getNumee();
        init_t=getElevList().get(i).getInit();
        prenume_e=getElevList().get(i).getPrene();
        
        //System.out.println(nr_e);
        
        me.ShowItemElev(nr_e,nume_e,init_t,prenume_e);         
       
        
        this.setVisible(false);
    }//GEN-LAST:event_tbl_listaeleviMouseClicked
    
    public void getInstance_MainExamen(MainExamen main) {         
        me = main;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaElevi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaElevi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaElevi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaElevi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaElevi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_listaelevi;
    // End of variables declaration//GEN-END:variables
}
