/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectbd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class MainL extends javax.swing.JFrame {

    /**
     * Creates new form MainEl
     */
    public MainL() {
        initComponents();
        getConnection();
        Show_Lucrare();
    }
    int pos = 0;
    
     public Connection getConnection(){
        Connection con=null;
        
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examencapacitate","root","");
           // JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(MainSc.class.getName()).log(Level.SEVERE, null, ex);
           // JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }
    }
     
      public boolean checkInputs(){
        if( txt_nrl.getText()==null
               
                ||txt_data.getText()==null
                ||txt_nota.getText()==null
                ||txt_nreL.getText()==null
                ||txt_nrcL.getText()==null)
        {return false;}else
        {
        return true;}
        
    }
      
      public ArrayList<Lucrare> getLucrareList(){
             ArrayList<Lucrare> lucrareList= new ArrayList<Lucrare>();
            Connection con= getConnection();
            String query = "SELECT * FROM lucrare";
            
            Statement st;
            ResultSet rs;
        try {
            
            
            st = con.createStatement();
            rs = st.executeQuery(query);
            Lucrare lucrare;
            while(rs.next()){
                lucrare = new Lucrare(rs.getInt("nr_l"),rs.getString("disciplina"),rs.getString("data"),rs.getFloat("nota"),rs.getInt("nr_e"),rs.getInt("nr_c"));
                lucrareList.add(lucrare);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainSc.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lucrareList;
        
    }
    
    
    public void Show_Lucrare(){
        ArrayList<Lucrare> list = getLucrareList();
        DefaultTableModel model= (DefaultTableModel)tbl_lucrare.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i= 0;i< list.size();i++){
            row[0]= list.get(i).getLnr();
            row[1]= list.get(i).getLdisciplina();
            row[2]= list.get(i).getLdata();
            row[3]= list.get(i).getLnota();
            row[4]= list.get(i).getLnre();
            row[5]= list.get(i).getLnrc();
            
         
            
            model.addRow(row);
            
            
        }
        
    }
    
    
    public void ShowItem(int index){
        txt_nrl.setText(Integer.toString(getLucrareList().get(index).getLnr()));
        combo_disc.setSelectedItem(getLucrareList().get(index).getLdisciplina().toString());
        txt_data.setText(getLucrareList().get(index).getLdata());
        txt_nota.setText(Float.toString(getLucrareList().get(index).getLnota()));
        txt_nreL.setText(Integer.toString(getLucrareList().get(index).getLnre()));
        txt_nrcL.setText(Integer.toString(getLucrareList().get(index).getLnrc()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nrl = new javax.swing.JTextField();
        txt_data = new javax.swing.JTextField();
        txt_nota = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_primul = new javax.swing.JButton();
        btn_urmatorul = new javax.swing.JButton();
        btn_anteriorul = new javax.swing.JButton();
        btn_ultimul = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nreL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lucrare = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_inapoi_e = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_nrcL = new javax.swing.JTextField();
        combo_disc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(254, 254, 242));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Disciplina:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numar Lucrare:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nota:");

        txt_nrl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nrlActionPerformed(evt);
            }
        });

        txt_data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_nota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.setToolTipText("");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.setToolTipText("");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setToolTipText("");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_primul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_primul.setText("Primul");
        btn_primul.setToolTipText("");
        btn_primul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primulActionPerformed(evt);
            }
        });

        btn_urmatorul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_urmatorul.setText("Urmatorul");
        btn_urmatorul.setToolTipText("");
        btn_urmatorul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urmatorulActionPerformed(evt);
            }
        });

        btn_anteriorul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_anteriorul.setText("Anteriorul");
        btn_anteriorul.setToolTipText("");
        btn_anteriorul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorulActionPerformed(evt);
            }
        });

        btn_ultimul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ultimul.setText("Ultimul");
        btn_ultimul.setToolTipText("");
        btn_ultimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimulActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Numar Elev:");

        txt_nreL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nreL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nreLActionPerformed(evt);
            }
        });

        tbl_lucrare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numar lucrare", "Disciplina", "Data", "Nota", "Numar elev", "Numar corector"
            }
        ));
        tbl_lucrare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lucrareMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_lucrare);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("LUCRARE");

        btn_inapoi_e.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_inapoi_e.setText("Inapoi");
        btn_inapoi_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inapoi_eActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Numar Corector:");

        txt_nrcL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nrcL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nrcLActionPerformed(evt);
            }
        });

        combo_disc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combo_disc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romana", "Matematica" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addComponent(btn_inapoi_e, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_data, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_nota, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txt_nrl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nreL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nrcL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_disc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(247, 247, 247)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_primul, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_urmatorul)
                .addGap(32, 32, 32)
                .addComponent(btn_anteriorul, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_ultimul, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_inapoi_e))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nrl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_disc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nreL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nrcL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_primul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_urmatorul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_anteriorul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ultimul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nrlActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed

        if(checkInputs() && txt_nrl !=null){
            Connection con=getConnection();

            try {
                PreparedStatement ps=con.prepareStatement("INSERT INTO lucrare (disciplina,data,nota,nr_e,nr_c)"
                    +" values (?,?,?,?,?);");
                
                ps.setString(1, combo_disc.getSelectedItem().toString());
                ps.setString(2,txt_data.getText());
                ps.setString(3,txt_nota.getText());
                ps.setString(4,txt_nreL.getText());
                ps.setString(5,txt_nrcL.getText());
                ps.executeUpdate();
                Show_Lucrare();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Unul sau mai multe campuri sunt goale");
        }
        
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if(checkInputs() && txt_nrl.getText()!= null){
            String update= null;
            PreparedStatement ps=null;
            Connection con= getConnection();
            try{
                update="UPDATE lucrare SET disciplina =?, data = ?, nota = ?,nr_e =?, nr_c=? WHERE nr_l = ?";
                ps=con.prepareStatement(update);
                ps.setString(1, combo_disc.getSelectedItem().toString());
                ps.setString(2, txt_data.getText());
                ps.setString(3, txt_nota.getText());
                ps.setString(4 ,txt_nreL.getText());
                ps.setString(5 ,txt_nrcL.getText());
                ps.setInt(6, Integer.parseInt( txt_nrl.getText()));
                ps.executeUpdate();
                Show_Lucrare();}
            catch(SQLException ex){
                Logger.getLogger(MainSc.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if(!txt_nrl.getText().equals("")){
            try {
                Connection con= getConnection();
                PreparedStatement ps= con.prepareStatement("DELETE FROM lucrare WHERE nr_l = ?");
                int nr_l= Integer.parseInt(txt_nrl.getText());
                ps.setInt(1, nr_l);
                ps.executeUpdate();
                Show_Lucrare();
                JOptionPane.showMessageDialog(null,"Lucrarea a fost stearsa.");

            } catch (SQLException ex) {
                Logger.getLogger(MainSc.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Lucrarea nu a fost stearsa.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Lucrarea nu a fost stearsa, introduceti numarul lucrarii.");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_primulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primulActionPerformed

        pos= 0;
        ShowItem(pos);
    }//GEN-LAST:event_btn_primulActionPerformed

    private void btn_urmatorulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urmatorulActionPerformed

        pos++;
        if(pos >=getLucrareList().size()){
            pos = getLucrareList().size()-1;

        }
        ShowItem(pos);
    }//GEN-LAST:event_btn_urmatorulActionPerformed

    private void btn_anteriorulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorulActionPerformed

        pos--;
        if(pos < 0){
            pos= 0;
        }
        ShowItem(pos);
    }//GEN-LAST:event_btn_anteriorulActionPerformed

    private void btn_ultimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimulActionPerformed

        pos= getLucrareList().size()-1;
        ShowItem(pos);
    }//GEN-LAST:event_btn_ultimulActionPerformed

    private void txt_nreLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nreLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nreLActionPerformed

    private void tbl_lucrareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lucrareMouseClicked
        int i= tbl_lucrare.getSelectedRow();
        TableModel model= tbl_lucrare.getModel();
        txt_nrl.setText(model.getValueAt(i, 0).toString());
        combo_disc.setSelectedItem(model.getValueAt(i, 1).toString());
        txt_data.setText(model.getValueAt(i, 2).toString());
        txt_nota.setText(model.getValueAt(i, 3).toString());
        txt_nreL.setText(model.getValueAt(i, 4).toString());
        txt_nrcL.setText(model.getValueAt(i, 5).toString());
            
    }//GEN-LAST:event_tbl_lucrareMouseClicked

    private void btn_inapoi_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inapoi_eActionPerformed
        // TODO add your handling code here:
        new MainProiectBD().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inapoi_eActionPerformed

    private void txt_nrcLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nrcLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nrcLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anteriorul;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_inapoi_e;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_primul;
    private javax.swing.JButton btn_ultimul;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_urmatorul;
    private javax.swing.JComboBox<String> combo_disc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_lucrare;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_nota;
    private javax.swing.JTextField txt_nrcL;
    private javax.swing.JTextField txt_nreL;
    private javax.swing.JTextField txt_nrl;
    // End of variables declaration//GEN-END:variables
}
